version: "3.9"

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
    env_file: .postgres.env
    restart: always
  web:
    build: ./web/.
    restart: always
    volumes:
      - ./web:/app
    ports:
      - "80:8000"
    environment:
      - USING_DOCKER=1
    depends_on:
      - postgres
    command: >
            bash -c "./manage.py migrate
            && ./manage.py runserver 0.0.0.0:8000"
