# Generated by Django 4.0.1 on 2022-01-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clicks", models.PositiveIntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "conversion_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("conversions", models.PositiveIntegerField()),
                ("search_term", models.CharField(max_length=255)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.adgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
