# Generated by Django 4.0.1 on 2022-01-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchterm",
            unique_together={("date", "ad_group", "search_term")},
        ),
    ]
